### ISSUE TITLE
Integrate is very slow compared to quadgen

### ISSUE THREAD

**Issue by antoine-levitt** [maltezfaria/ImplicitIntegration.jl#8] opened 2024-10-10 07:36 UTC
I can't make `integrate(int, F, lc, hc; surface=true, tol=1e-4)` give me a result in a sensible time; quadgen is fine. Is there a way to make quadgk be quicker for relatively coarse integrals?

**Comment by maltezfaria** [comment] 2024-10-10 07:46
At the moment we use `HCubature`, which is usually more efficient than just a tensor product of `quadgk` calls. Unfortunately, `HCubature` does not allow passing an `order` parameter. I could use `quadgk` and expose the `order` parameter, but I wonder if the issue is really coming from this...

**Comment by antoine-levitt** [comment] 2024-10-10 08:06
On graphene (2D) it works fine, and I get approximately the same amount of evals for 
```

COUNT = 0
@time Q = ImplicitIntegration.quadgen(k -> (global COUNT += 1; abs(f(k)) - (.3)), lc, hc; surface=true, order=10)
println(COUNT)

COUNT = 0
@time Q = ImplicitIntegration.integrate(k -> one(eltype(k)), k -> (global COUNT += 1; abs(f(k)) - (.3)), lc, hc; surface=true, tol=1e-4)
println(COUNT)
```
On SrVO3, I've stopped the computation at [402.35, 3.45, 221.42, 3.04] (ie it's doing a lot of phi and nabla phi evals)

**Comment by antoine-levitt** [comment] 2024-10-11 07:31
A simple self-contained reproducer:
```
using StaticArrays

const lattice = @SMatrix [3/2 3/2;
                          sqrt(3)/2 -sqrt(3)/2]
const δ1 = lattice \ ((@SVector [1; sqrt(3)]) / 2)
const δ2 = lattice \ ((@SVector [1; -sqrt(3)]) / 2)
const δ3 = lattice \ (-@SVector [1; 0])
f(k) = sum(cis(2π*dot(k, δ)) for δ in (δ1, δ2, δ3))
∇f(k) = sum(2π * im * (δ) * cis(2π*dot(k, δ)) for δ in (δ1, δ2, δ3))
∂f∂k(k, i) = sum(2π * im * δ[i] * cis(2π*dot(k, δ)) for δ in (δ1, δ2, δ3))

H(k) = @SMatrix [0 f(k); conj(f(k)) 0]
∂H∂k(k, i) = @SMatrix [0 ∂f∂k(k, i); conj(∂f∂k(k, i)) 0]

using IntervalArithmetic
using ForwardDiff
using StaticArrays
using Roots
using ImplicitIntegration

lc = (0, 0, 0)
hc = (1, 1, 1)

COUNT = 0; 
ϕ(k) = (global COUNT += 1; abs(f(k[1:2])) - k[3]^2 - .3)

@time Q = ImplicitIntegration.quadgen(ϕ, lc, hc; surface=true, order=1, log=true)
println(COUNT)

COUNT = 0
@time Q = ImplicitIntegration.quadgen(ϕ, lc, hc; surface=true, order=10, log=true)
println(COUNT)

COUNT = 0
@time Q = ImplicitIntegration.integrate(k -> one(eltype(k)), ϕ, lc, hc; surface=true, tol=1e-4, log=true)
println(COUNT)

```

**Comment by antoine-levitt** [comment] 2024-10-11 07:35
Respectively 50^3, 140^3 and 350^3 calls to phi. I guess it's not that unexpected, but 350^3 is a lot of evals. That example looks like a good benchmark btw

**Comment by antoine-levitt** [comment] 2024-10-11 08:06
Sorry that example was a bit degenerate, will come up with something nicer

**Comment by antoine-levitt** [comment] 2024-10-11 08:42
OK, more relevant example
`ϕ(k) = (global COUNT += 1; abs(f(k[1:2])) - (sin(2π*k[3])^2 + 1.5))`
That's a nice periodic function, easy to compute and differentiate. abs(f) ranges from 0 to 3 and is smooth except at the endpoints, with a critical value at 1. So I make the other term vary between 1.5 and 2.5, where everything is nice, and this results in a nice surface. There, when I used perfect (stochastic) bounds, I get, for order=1, order=10 and integrate w/ tol=1e-3 (always in cbrt of phi evals)
```
4.464745095584537
11.773530633766672
34.499544907530435
```
So integrate is OK, it's just much slower. What I was seeing before is that it also is much more sensitive to degenerate cases (where the surface is not smooth).

**Comment by maltezfaria** [comment] 2024-10-29 12:49
I guess we can close this right? I don't think there is anything fundamentally flawed with `integrate`; in fact, `quadgen` calls `integrate` with a hacky integrand that creates a quadrature instead of computing a value.

**Closed as completed by maltezfaria** 2024-10-29 12:49 UTC
